export const MBTIs = [
  "ISFP (호기심 많은 예술가)",
  "ISFJ (용감한 수호자)",
  "ISTP (만능재주꾼)",
  "ISTJ (청렴결백 논리주의자)",
  "INFP (열정적인 중재자)",
  "INFJ (선의의 옹호자)",
  "INTP (논리적 사색가)",
  "INTJ (용의주도한 전략가)",
  "ESFP (자유영혼 연예인)",
  "ESFJ (사교적인 외교관)",
  "ESTP (모험을 즐기는 사업가)",
  "ESTJ (엄격한 관리자)",
  "ENFP (재기발랄한 활동가)",
  "ENFJ (정의로운 사회운동가)",
  "ENTP (논쟁을 즐기는 변론가)",
  "ENTJ (대담한 통솔가)",
  "모름",
];

export const MBTIToIndex = {
  ISFP: 0,
  ISFJ: 1,
  ISTP: 2,
  ISTJ: 3,
  INFP: 4,
  INFJ: 5,
  INTP: 6,
  INTJ: 7,
  ESFP: 8,
  ESFJ: 9,
  ESTP: 10,
  ESTJ: 11,
  ENFP: 12,
  ENFJ: 13,
  ENTP: 14,
  ENTJ: 15,
  모름: 16,
};

export const IndexToMBTI = {
  0: "ISFP",
  1: "ISFJ",
  2: "ISTP",
  3: "ISTJ",
  4: "INFP",
  5: "INFJ",
  6: "INTP",
  7: "INTJ",
  8: "ESFP",
  9: "ESFJ",
  10: "ESTP",
  11: "ESTJ",
  12: "ENFP",
  13: "ENFJ",
  14: "ENTP",
  15: "ENTJ",
  16: "모름",
};

export const DrinkingStyles = [
  "안마셔요",
  "가끔",
  "술은 분위기상",
  "메뉴가 좋으면 못 참지!",
  "술은 인생의 동반자",
];
